---

- hosts: vagrant
  vars:
    apache:
        hostname: zigmoney.dev
        user: vagrant
        group: vagrant
    php:
        error_reporting: E_ALL
        display_errors: On
        display_startup_errors: On
        error_log: /workspace/log/php5/error.log
        date_timezone: America/New_York
        sendmail_path: "/usr/bin/env catchmail"
        sendmail_from: "service@zigmoney.dev"
    git:
        repository: "https://github.com/selasegithub/zidisha-vagrant"
    database:
        host: 127.0.0.1
        name: zigmoney
        user: zigmoney
        password: zigmoney
    paths:
        full: /workspace/zidisha/
        root: /workspace/zidisha/
        log: /workspace/log/
    site_url: http://zigmoney.dev/

  roles:
    - common
    - { role: perlmonkey.role-mailcatcher, sudo: yes }
    - database
    - webserver
    - zidisha
